[clickIDY_cancas_1(p)] ~ [] (8,0) Skip
[clickIDY_submit_order(p)] ~ [] (6,0) Skip
[clickIDY_cancas_19(p)] ~ [] (5,0) Skip
[clickIDY_cancas_17(p)] ~ [] (2,0) Skip
[closeIDY_filterPanel_comboboxSeries(p)] ~ [] (13,0) Skip
[openIDY_filterPanel_comboboxSeries(p)] ~ [] (13,0) Skip
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p)] ~ [] (14,0) Skip
[clickIDY_checkout_submit(p)] ~ [] (15,0) Skip
[typeIDY_checkout_phonenr(p)] ~ [] (12,0) Skip
[typeIDY_checkout_zipcode(p)] ~ [] (11,0) Skip
[typeIDY_checkout_address(p)] ~ [] (13,0) Skip
[typeIDY_checkout_fullname(p)] ~ [] (9,0) Skip
[clickIDY_checkout_fullname(p)] ~ [] (13,0) Skip
[clickIDY_CatTitleBtns_label_viewCart(p)] ~ [] (2,0) Skip
[clickIDY_cancas_14(p)] ~ [] (5,0) Skip
[clickIDY_textFeature_14(p)] ~ [] (2,0) Skip
[clickIDY_filterPanel_buttonGo(p)] ~ [] (7,0) Skip
[typeIDY_filterPanel_txtInputFind(p)] ~ [] (4,0) Skip
[clickIDY_filterPanel_txtInputFind(p)] ~ [] (3,0) Skip
[clickImage7(p)] ~ [] (23,0) Skip
[clickIDY_cancas_10(p)] ~ [] (2,0) Skip
[clickIDY_cancas_11(p)] ~ [] (6,0) Skip
[clickIDY_cancas_12(p)] ~ [] (3,0) Skip
[clickIDY_cancas_8(p)] ~ [] (3,0) Skip
[clickIDY_cancas_7(p)] ~ [] (3,0) Skip
[clickfeat_prod_1(p)] ~ [] (3,0) Skip
[clickIDY_buttonLogin(p)] ~ [] (4,0) Skip
[clickOK(p)] ~ [] (40,0) Skip
[clickIDY_buttonSearch(p)] ~ [] (4,0) Skip
[clickIDY_searchproduct(p)] ~ [] (3,0) Skip
[clickImage3(p)] ~ [] (7,0) Skip
[clickImage4(p)] ~ [] (6,0) Skip
[clickImage2(p)] ~ [] (6,0) Skip
[clickIDY_compareCart_labelName_20(p)] ~ [] (7,0) Skip
[clickIDY_compareCart_labelName_14(p)] ~ [] (2,0) Skip
[clickIDY_compareCart_labelName_13(p)] ~ [] (6,0) Skip
[clickHID_IDY_priceSlider_0_4_0_button(p)] ~ [] (7,0) Skip
[clickIDY_cancas_13(p)] ~ [] (3,0) Skip
[clickIDY_cancas_15(p)] ~ [] (2,0) Skip
[clickIDY_buttonLocate(p)] ~ [] (5,0) Skip
[closeIDY_addressState(p)] ~ [] (7,0) Skip
[changeIDY_addressState(p)] ~ [] (4,0) Skip
[openIDY_addressState(p)] ~ [] (7,0) Skip
[clickHID_IDY_addressState_1_button(p)] ~ [] (8,0) Skip
[clickIDY_cancas_16(p)] ~ [] (2,0) Skip
[clickIDY_VideoButton(p)] ~ [] (4,0) Skip
[clickIDY_textFeature_11(p)] ~ [] (2,0) Skip
[clickIDY_filterPanel_labelCompare(p)] ~ [] (4,0) Skip
[clickHID_IDY_priceSlider_0_4_1_button(p)] ~ [] (5,0) Skip
[typeIDY_addressStreet(p)] ~ [] (4,0) Skip
[clickIDY_addressStreet(p)] ~ [] (4,0) Skip
[clickIDY_checkout_phonenr(p)] ~ [] (11,0) Skip
[clickIDY_textFeature_20(p)] ~ [] (3,0) Skip
[typeIDY_myphonenr2(p)] ~ [] (2,0) Skip
[typeIDY_myphonenr1(p)] ~ [] (2,0) Skip
[clickIDY_myphonenr2(p)] ~ [] (2,0) Skip
[clickIDY_myphonenr1(p)] ~ [] (3,0) Skip
[clickIDY_checkbox_remember(p)] ~ [] (2,0) Skip
[clickIDY_textFeature_3(p)] ~ [] (2,0) Skip
[clickImage6(p)] ~ [] (4,0) Skip
[clickIDY_checkout_zipcode(p)] ~ [] (11,0) Skip
[clickIDY_checkout_address(p)] ~ [] (2,0) Skip
[clickback_thumb(p)] ~ [] (2,0) Skip
[clickIDY_addressZip(p)] ~ [] (3,0) Skip
[clickIDY_addresscity(p)] ~ [] (3,0) Skip
[clickIDY_pwd(p)] ~ [] (2,0) Skip
[itemclickButtonBar0(p);changeTabNavigator0(q)] ~ [changeTabNavigator0(q)] (3,0) Zero
[clickOK(p);changeTabNavigator0(q)] ~ [changeTabNavigator0(q)] (3,0) Zero
[clickIDY_VideoButton(p);changeTabNavigator0(q)] ~ [changeTabNavigator0(q)] (2,0) Zero
[clickIDY_cancas_1(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (10,0) Zero
[clickIDY_filterPanel_cbTriband(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (3,0) Zero
[clickIDY_checkout_fullname(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (5,0) Zero
[clickIDY_CatTitleBtns_label_viewCart(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (3,0) Zero
[clickIDY_filterPanel_labelFind(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (3,0) Zero
[clickImage7(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (19,0) Zero
[clickIDY_cancas_10(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (3,0) Zero
[clickIDY_cancas_12(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (8,0) Zero
[clickOK(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (57,0) Zero
[clickImage4(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (9,0) Zero
[clickImage2(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (5,0) Zero
[clickHID_IDY_priceSlider_0_4_0_button(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (3,0) Zero
[changeIDY_priceSlider(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (8,0) Zero
[closeIDY_addressState(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (5,0) Zero
[clickIDY_cancas_5(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (4,0) Zero
[clickIDY_pwd(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (10,0) Zero
[clickIDY_cartGrip_img1(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (6,0) Zero
[clickIDY_cancas_20(p);clickIDY_submit_order(q)] ~ [clickIDY_submit_order(q)] (2,0) Zero
[clickIDY_compare_20(p);clickIDY_cancas_20(q)] ~ [clickIDY_cancas_20(q)] (4,0) Zero
[clickIDY_textFeature_20(p);clickIDY_cancas_20(q)] ~ [clickIDY_cancas_20(q)] (3,0) Zero
[clickIDY_filterPanel_cbCamera(p);clickIDY_filterPanel_cbVideo(q)] ~ [clickIDY_filterPanel_cbVideo(q)] (4,0) Zero
[openIDY_filterPanel_comboboxSeries(p);closeIDY_filterPanel_comboboxSeries(q)] ~ [closeIDY_filterPanel_comboboxSeries(q)] (2,0) Zero
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p);openIDY_filterPanel_comboboxSeries(q)] ~ [openIDY_filterPanel_comboboxSeries(q)] (13,0) Zero
[itemclickButtonBar0(p);clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] ~ [clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] (2,0) Zero
[openIDY_filterPanel_comboboxSeries(p);clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] ~ [clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] (2,0) Zero
[clickIDY_CatTitleBtns_label_findPhones(p);clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] ~ [clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] (3,0) Zero
[clickHID_IDY_priceSlider_0_4_0_button(p);clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] ~ [clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] (2,0) Zero
[closeIDY_filterPanel_comboboxSeries(p);clickIDY_filterPanel_cbCamera(q)] ~ [clickIDY_filterPanel_cbCamera(q)] (4,0) Zero
[changeIDY_priceSlider(p);clickIDY_filterPanel_cbCamera(q)] ~ [clickIDY_filterPanel_cbCamera(q)] (2,0) Zero
[changeIDY_priceSlider(p);clickIDY_filterPanel_cbTriband(q)] ~ [clickIDY_filterPanel_cbTriband(q)] (2,0) Zero
[itemclickButtonBar0(p);clickIDY_checkout_submit(q)] ~ [clickIDY_checkout_submit(q)] (4,0) Zero
[typeIDY_checkout_phonenr(p);clickIDY_checkout_submit(q)] ~ [clickIDY_checkout_submit(q)] (7,0) Zero
[clickOK(p);clickIDY_checkout_submit(q)] ~ [clickIDY_checkout_submit(q)] (9,0) Zero
[clickIDY_checkout_phonenr(p);clickIDY_checkout_submit(q)] ~ [clickIDY_checkout_submit(q)] (3,0) Zero
[typeIDY_checkout_zipcode(p);typeIDY_checkout_phonenr(q)] ~ [typeIDY_checkout_phonenr(q)] (11,0) Zero
[clickIDY_checkout_phonenr(p);typeIDY_checkout_phonenr(q)] ~ [typeIDY_checkout_phonenr(q)] (4,0) Zero
[typeIDY_checkout_address(p);typeIDY_checkout_zipcode(q)] ~ [typeIDY_checkout_zipcode(q)] (6,0) Zero
[clickIDY_checkout_phonenr(p);typeIDY_checkout_zipcode(q)] ~ [typeIDY_checkout_zipcode(q)] (4,0) Zero
[clickIDY_checkout_zipcode(p);typeIDY_checkout_zipcode(q)] ~ [typeIDY_checkout_zipcode(q)] (8,0) Zero
[typeIDY_checkout_fullname(p);typeIDY_checkout_address(q)] ~ [typeIDY_checkout_address(q)] (11,0) Zero
[clickIDY_checkout_fullname(p);typeIDY_checkout_fullname(q)] ~ [typeIDY_checkout_fullname(q)] (8,0) Zero
[itemclickButtonBar0(p);clickIDY_checkout_fullname(q)] ~ [clickIDY_checkout_fullname(q)] (6,0) Zero
[clickIDY_submit_order(p);clickIDY_checkout_fullname(q)] ~ [clickIDY_checkout_fullname(q)] (7,0) Zero
[clickIDY_textFeature_3(p);clickIDY_cancas_3(q)] ~ [clickIDY_cancas_3(q)] (2,0) Zero
[changeTabNavigator0(p);clickIDY_compare_this(q)] ~ [clickIDY_compare_this(q)] (2,0) Zero
[clickIDY_textFeature_14(p);clickIDY_cancas_14(q)] ~ [clickIDY_cancas_14(q)] (2,0) Zero
[typeIDY_filterPanel_txtInputFind(p);clickIDY_filterPanel_buttonGo(q)] ~ [clickIDY_filterPanel_buttonGo(q)] (3,0) Zero
[clickOK(p);clickIDY_filterPanel_buttonGo(q)] ~ [clickIDY_filterPanel_buttonGo(q)] (2,0) Zero
[clickIDY_filterPanel_txtInputFind(p);typeIDY_filterPanel_txtInputFind(q)] ~ [typeIDY_filterPanel_txtInputFind(q)] (3,0) Zero
[itemclickButtonBar0(p);clickIDY_CatTitleBtns_label_findPhones(q)] ~ [clickIDY_CatTitleBtns_label_findPhones(q)] (7,0) Zero
[clickIDY_cancas_3(p);clickIDY_CatTitleBtns_label_findPhones(q)] ~ [clickIDY_CatTitleBtns_label_findPhones(q)] (2,0) Zero
[itemclickButtonBar0(p);clickImage7(q)] ~ [clickImage7(q)] (11,0) Zero
[closeIDY_addressState(p);clickImage7(q)] ~ [clickImage7(q)] (6,0) Zero
[clickIDY_addressStreet(p);clickImage7(q)] ~ [clickImage7(q)] (6,0) Zero
[clickImage6(p);clickImage7(q)] ~ [clickImage7(q)] (12,0) Zero
[clickIDY_textFeature_11(p);clickIDY_cancas_11(q)] ~ [clickIDY_cancas_11(q)] (3,0) Zero
[clickIDY_compare_11(p);clickIDY_cancas_11(q)] ~ [clickIDY_cancas_11(q)] (2,0) Zero
[clickIDY_cancas_8(p);clickIDY_purchase_12(q)] ~ [clickIDY_purchase_12(q)] (2,0) Zero
[itemclickButtonBar0(p);clickIDY_purchase_1(q)] ~ [clickIDY_purchase_1(q)] (2,0) Zero
[clickIDY_checkbox_remember(p);clickIDY_buttonLogin(q)] ~ [clickIDY_buttonLogin(q)] (4,0) Zero
[clickIDY_checkout_submit(p);clickOK(q)] ~ [clickOK(q)] (28,0) Zero
[typeIDY_checkout_phonenr(p);clickOK(q)] ~ [clickOK(q)] (5,0) Zero
[clickIDY_filterPanel_buttonGo(p);clickOK(q)] ~ [clickOK(q)] (10,0) Zero
[clickIDY_buttonLogin(p);clickOK(q)] ~ [clickOK(q)] (8,0) Zero
[clickIDY_buttonSearch(p);clickOK(q)] ~ [clickOK(q)] (8,0) Zero
[clickIDY_buttonLocate(p);clickOK(q)] ~ [clickOK(q)] (10,0) Zero
[typeIDY_myphonenr2(p);clickOK(q)] ~ [clickOK(q)] (2,0) Zero
[typeIDY_searchproduct(p);clickIDY_buttonSearch(q)] ~ [clickIDY_buttonSearch(q)] (3,0) Zero
[clickIDY_searchproduct(p);typeIDY_searchproduct(q)] ~ [typeIDY_searchproduct(q)] (4,0) Zero
[itemclickButtonBar0(p);clickIDY_searchproduct(q)] ~ [clickIDY_searchproduct(q)] (2,0) Zero
[clickfeat_prod_1(p);clickImage3(q)] ~ [clickImage3(q)] (3,0) Zero
[clickOK(p);clickImage3(q)] ~ [clickImage3(q)] (3,0) Zero
[clickfeat_prod_3(p);clickImage3(q)] ~ [clickImage3(q)] (3,0) Zero
[clickImage2(p);clickImage4(q)] ~ [clickImage4(q)] (4,0) Zero
[clickfeat_prod_1(p);clickImage2(q)] ~ [clickImage2(q)] (3,0) Zero
[clickOK(p);clickImage2(q)] ~ [clickImage2(q)] (2,0) Zero
[clickIDY_compareCart_labelName_14(p);clickIDY_compareCart_labelName_20(q)] ~ [clickIDY_compareCart_labelName_20(q)] (7,0) Zero
[clickIDY_compareCart_labelName_13(p);clickIDY_compareCart_labelName_14(q)] ~ [clickIDY_compareCart_labelName_14(q)] (2,0) Zero
[clickIDY_cancas_20(p);clickIDY_compareCart_labelName_13(q)] ~ [clickIDY_compareCart_labelName_13(q)] (6,0) Zero
[clickIDY_cancas_20(p);clickIDY_compare_20(q)] ~ [clickIDY_compare_20(q)] (2,0) Zero
[clickIDY_cancas_19(p);clickIDY_compare_20(q)] ~ [clickIDY_compare_20(q)] (2,0) Zero
[changeIDY_priceSlider(p);clickHID_IDY_priceSlider_0_4_0_button(q)] ~ [clickHID_IDY_priceSlider_0_4_0_button(q)] (9,0) Zero
[changeTabNavigator0(p);changeIDY_priceSlider(q)] ~ [changeIDY_priceSlider(q)] (2,0) Zero
[itemclickButtonBar0(p);changeIDY_priceSlider(q)] ~ [changeIDY_priceSlider(q)] (19,0) Zero
[clickIDY_cancas_14(p);changeIDY_priceSlider(q)] ~ [changeIDY_priceSlider(q)] (33,0) Zero
[openIDY_filterPanel_comboboxSeries(p);changeIDY_filterPanel_comboboxSeries(q)] ~ [changeIDY_filterPanel_comboboxSeries(q)] (10,0) Zero
[closeIDY_addressState(p);clickIDY_buttonLocate(q)] ~ [clickIDY_buttonLocate(q)] (2,0) Zero
[clickIDY_addressZip(p);clickIDY_buttonLocate(q)] ~ [clickIDY_buttonLocate(q)] (2,0) Zero
[changeIDY_addressState(p);closeIDY_addressState(q)] ~ [closeIDY_addressState(q)] (4,0) Zero
[openIDY_addressState(p);closeIDY_addressState(q)] ~ [closeIDY_addressState(q)] (2,0) Zero
[clickHID_IDY_addressState_1_button(p);closeIDY_addressState(q)] ~ [closeIDY_addressState(q)] (2,0) Zero
[openIDY_addressState(p);changeIDY_addressState(q)] ~ [changeIDY_addressState(q)] (3,0) Zero
[clickHID_IDY_addressState_1_button(p);openIDY_addressState(q)] ~ [openIDY_addressState(q)] (9,0) Zero
[itemclickButtonBar0(p);clickHID_IDY_addressState_1_button(q)] ~ [clickHID_IDY_addressState_1_button(q)] (6,0) Zero
[openIDY_addressState(p);clickHID_IDY_addressState_1_button(q)] ~ [clickHID_IDY_addressState_1_button(q)] (3,0) Zero
[clickIDY_addressStreet(p);clickHID_IDY_addressState_1_button(q)] ~ [clickHID_IDY_addressState_1_button(q)] (3,0) Zero
[changeTabNavigator0(p);clickIDY_VideoButton(q)] ~ [clickIDY_VideoButton(q)] (4,0) Zero
[clickOK(p);clickIDY_filterPanel_labelCompare(q)] ~ [clickIDY_filterPanel_labelCompare(q)] (2,0) Zero
[changeIDY_priceSlider(p);clickHID_IDY_priceSlider_0_4_1_button(q)] ~ [clickHID_IDY_priceSlider_0_4_1_button(q)] (5,0) Zero
[clickImage7(p);typeIDY_addressStreet(q)] ~ [typeIDY_addressStreet(q)] (3,0) Zero
[itemclickButtonBar0(p);clickIDY_addressStreet(q)] ~ [clickIDY_addressStreet(q)] (2,0) Zero
[typeIDY_checkout_phonenr(p);clickIDY_checkout_phonenr(q)] ~ [clickIDY_checkout_phonenr(q)] (9,0) Zero
[typeIDY_checkout_zipcode(p);clickIDY_checkout_phonenr(q)] ~ [clickIDY_checkout_phonenr(q)] (19,0) Zero
[clickOK(p);clickIDY_checkout_phonenr(q)] ~ [clickIDY_checkout_phonenr(q)] (9,0) Zero
[clickIDY_checkout_zipcode(p);clickIDY_checkout_phonenr(q)] ~ [clickIDY_checkout_phonenr(q)] (9,0) Zero
[clickIDY_myphonenr1(p);clickIDY_myphonenr2(q)] ~ [clickIDY_myphonenr2(q)] (2,0) Zero
[clickOK(p);clickIDY_checkbox_remember(q)] ~ [clickIDY_checkbox_remember(q)] (2,0) Zero
[typeIDY_pwd(p);clickIDY_checkbox_remember(q)] ~ [clickIDY_checkbox_remember(q)] (2,0) Zero
[itemclickButtonBar0(p);clickImage6(q)] ~ [clickImage6(q)] (3,0) Zero
[typeIDY_checkout_phonenr(p);clickIDY_checkout_zipcode(q)] ~ [clickIDY_checkout_zipcode(q)] (10,0) Zero
[typeIDY_checkout_address(p);clickIDY_checkout_zipcode(q)] ~ [clickIDY_checkout_zipcode(q)] (10,0) Zero
[clickIDY_checkout_phonenr(p);clickIDY_checkout_zipcode(q)] ~ [clickIDY_checkout_zipcode(q)] (20,0) Zero
[clickIDY_addresscity(p);clickIDY_addressZip(q)] ~ [clickIDY_addressZip(q)] (2,0) Zero
[clickIDY_addressStreet(p);clickIDY_addresscity(q)] ~ [clickIDY_addresscity(q)] (3,0) Zero
[changeTabNavigator0(p);changeTabNavigator0(q)] ~ [changeTabNavigator0(q)] (7,0) Idemp
[clickIDY_cancas_1(p);clickIDY_cancas_1(q)] ~ [clickIDY_cancas_1(q)] (2,0) Idemp
[itemclickButtonBar0(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (281,0) Idemp
[typeIDY_checkout_phonenr(p);typeIDY_checkout_phonenr(q)] ~ [typeIDY_checkout_phonenr(q)] (10,0) Idemp
[typeIDY_checkout_zipcode(p);typeIDY_checkout_zipcode(q)] ~ [typeIDY_checkout_zipcode(q)] (4,0) Idemp
[typeIDY_checkout_address(p);typeIDY_checkout_address(q)] ~ [typeIDY_checkout_address(q)] (22,0) Idemp
[typeIDY_checkout_fullname(p);typeIDY_checkout_fullname(q)] ~ [typeIDY_checkout_fullname(q)] (2,0) Idemp
[clickIDY_checkout_fullname(p);clickIDY_checkout_fullname(q)] ~ [clickIDY_checkout_fullname(q)] (12,0) Idemp
[clickIDY_compare_this(p);clickIDY_compare_this(q)] ~ [clickIDY_compare_this(q)] (3,0) Idemp
[typeIDY_filterPanel_txtInputFind(p);typeIDY_filterPanel_txtInputFind(q)] ~ [typeIDY_filterPanel_txtInputFind(q)] (2,0) Idemp
[clickImage7(p);clickImage7(q)] ~ [clickImage7(q)] (91,0) Idemp
[typeIDY_searchproduct(p);typeIDY_searchproduct(q)] ~ [typeIDY_searchproduct(q)] (2,0) Idemp
[clickImage3(p);clickImage3(q)] ~ [clickImage3(q)] (9,0) Idemp
[clickImage4(p);clickImage4(q)] ~ [clickImage4(q)] (8,0) Idemp
[clickImage2(p);clickImage2(q)] ~ [clickImage2(q)] (2,0) Idemp
[clickIDY_compareCart_labelName_20(p);clickIDY_compareCart_labelName_20(q)] ~ [clickIDY_compareCart_labelName_20(q)] (42,0) Idemp
[clickIDY_compareCart_labelName_14(p);clickIDY_compareCart_labelName_14(q)] ~ [clickIDY_compareCart_labelName_14(q)] (2,0) Idemp
[clickIDY_compareCart_labelName_13(p);clickIDY_compareCart_labelName_13(q)] ~ [clickIDY_compareCart_labelName_13(q)] (24,0) Idemp
[clickIDY_VideoButton(p);clickIDY_VideoButton(q)] ~ [clickIDY_VideoButton(q)] (2,0) Idemp
[clickIDY_filterPanel_labelCompare(p);clickIDY_filterPanel_labelCompare(q)] ~ [clickIDY_filterPanel_labelCompare(q)] (2,0) Idemp
[typeIDY_addressStreet(p);typeIDY_addressStreet(q)] ~ [typeIDY_addressStreet(q)] (6,0) Idemp
[clickIDY_checkout_phonenr(p);clickIDY_checkout_phonenr(q)] ~ [clickIDY_checkout_phonenr(q)] (36,0) Idemp
[clickImage6(p);clickImage6(q)] ~ [clickImage6(q)] (6,0) Idemp
[clickIDY_checkout_zipcode(p);clickIDY_checkout_zipcode(q)] ~ [clickIDY_checkout_zipcode(q)] (60,0) Idemp
[clickIDY_addressZip(p);clickIDY_addressZip(q)] ~ [clickIDY_addressZip(q)] (2,0) Idemp
[clickIDY_addresscity(p);clickIDY_addresscity(q)] ~ [clickIDY_addresscity(q)] (2,0) Idemp
[clickImage7(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q);clickImage7(p)] (2,0) Com
[clickOK(p);clickIDY_checkout_submit(q)] ~ [clickIDY_checkout_submit(q);clickOK(p)] (8,0) Com
[clickOK(p);clickIDY_filterPanel_buttonGo(q)] ~ [clickIDY_filterPanel_buttonGo(q);clickOK(p)] (2,0) Com
[clickIDY_compare_20(p);clickIDY_cancas_20(q)] ~ [clickIDY_cancas_20(q);clickIDY_compare_20(p)] (2,0) Com
[changeIDY_priceSlider(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q);changeIDY_priceSlider(p)] (2,0) Com
[clickHID_IDY_addressState_1_button(p);openIDY_addressState(q)] ~ [openIDY_addressState(q);clickHID_IDY_addressState_1_button(p)] (2,0) Com
[clickHID_IDY_priceSlider_0_4_1_button(p);changeIDY_priceSlider(q)] ~ [changeIDY_priceSlider(q);clickHID_IDY_priceSlider_0_4_1_button(p)] (2,0) Com
[clickIDY_checkout_phonenr(p);typeIDY_checkout_zipcode(q)] ~ [typeIDY_checkout_zipcode(q);clickIDY_checkout_phonenr(p)] (2,0) Com
[clickIDY_checkout_zipcode(p);clickIDY_checkout_phonenr(q)] ~ [clickIDY_checkout_phonenr(q);clickIDY_checkout_zipcode(p)] (2,0) Com
[changeTabNavigator0(p);clickIDY_VideoButton(q)] ~ [] (3,0) Inv
[itemclickButtonBar0(p);clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] ~ [] (2,0) Inv
[itemclickButtonBar0(p);clickIDY_checkout_fullname(q)] ~ [] (4,0) Inv
[itemclickButtonBar0(p);clickIDY_CatTitleBtns_label_findPhones(q)] ~ [] (6,0) Inv
[itemclickButtonBar0(p);clickImage7(q)] ~ [] (2,0) Inv
[itemclickButtonBar0(p);clickIDY_searchproduct(q)] ~ [] (2,0) Inv
[itemclickButtonBar0(p);clickHID_IDY_addressState_1_button(q)] ~ [] (4,0) Inv
[itemclickButtonBar0(p);clickIDY_addressStreet(q)] ~ [] (2,0) Inv
[clickIDY_submit_order(p);clickIDY_checkout_fullname(q)] ~ [] (5,0) Inv
[clickIDY_cancas_20(p);clickIDY_submit_order(q)] ~ [] (2,0) Inv
[closeIDY_filterPanel_comboboxSeries(p);changeIDY_priceSlider(q)] ~ [] (2,0) Inv
[openIDY_filterPanel_comboboxSeries(p);closeIDY_filterPanel_comboboxSeries(q)] ~ [] (2,0) Inv
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p);openIDY_filterPanel_comboboxSeries(q)] ~ [] (13,0) Inv
[clickIDY_checkout_submit(p);clickOK(q)] ~ [] (13,0) Inv
[typeIDY_checkout_phonenr(p);clickIDY_checkout_submit(q)] ~ [] (5,0) Inv
[typeIDY_checkout_phonenr(p);typeIDY_checkout_phonenr(q)] ~ [] (3,0) Inv
[typeIDY_checkout_phonenr(p);clickOK(q)] ~ [] (2,0) Inv
[typeIDY_checkout_zipcode(p);typeIDY_checkout_phonenr(q)] ~ [] (7,0) Inv
[typeIDY_checkout_zipcode(p);clickIDY_checkout_phonenr(q)] ~ [] (3,0) Inv
[typeIDY_checkout_address(p);typeIDY_checkout_zipcode(q)] ~ [] (6,0) Inv
[typeIDY_checkout_address(p);typeIDY_checkout_address(q)] ~ [] (5,0) Inv
[typeIDY_checkout_fullname(p);typeIDY_checkout_address(q)] ~ [] (6,0) Inv
[clickIDY_checkout_fullname(p);typeIDY_checkout_fullname(q)] ~ [] (7,0) Inv
[clickIDY_checkout_fullname(p);clickIDY_checkout_fullname(q)] ~ [] (4,0) Inv
[clickIDY_textFeature_14(p);clickIDY_cancas_14(q)] ~ [] (2,0) Inv
[clickIDY_filterPanel_buttonGo(p);clickOK(q)] ~ [] (6,0) Inv
[typeIDY_filterPanel_txtInputFind(p);clickIDY_filterPanel_buttonGo(q)] ~ [] (2,0) Inv
[clickIDY_filterPanel_txtInputFind(p);typeIDY_filterPanel_txtInputFind(q)] ~ [] (2,0) Inv
[clickIDY_CatTitleBtns_label_findPhones(p);clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] ~ [] (3,0) Inv
[clickImage7(p);itemclickButtonBar0(q)] ~ [] (4,0) Inv
[clickImage7(p);clickImage7(q)] ~ [] (16,0) Inv
[clickfeat_prod_1(p);clickImage2(q)] ~ [] (2,0) Inv
[clickIDY_buttonLogin(p);clickOK(q)] ~ [] (3,0) Inv
[clickOK(p);itemclickButtonBar0(q)] ~ [] (14,0) Inv
[clickOK(p);clickIDY_checkout_submit(q)] ~ [] (3,0) Inv
[clickOK(p);changeIDY_priceSlider(q)] ~ [] (3,0) Inv
[clickIDY_buttonSearch(p);clickOK(q)] ~ [] (4,0) Inv
[typeIDY_searchproduct(p);clickIDY_buttonSearch(q)] ~ [] (3,0) Inv
[clickIDY_searchproduct(p);typeIDY_searchproduct(q)] ~ [] (3,0) Inv
[clickImage3(p);clickImage3(q)] ~ [] (3,0) Inv
[clickImage4(p);itemclickButtonBar0(q)] ~ [] (2,0) Inv
[clickImage4(p);clickImage4(q)] ~ [] (2,0) Inv
[clickImage2(p);itemclickButtonBar0(q)] ~ [] (3,0) Inv
[clickIDY_compareCart_labelName_20(p);clickIDY_compareCart_labelName_20(q)] ~ [] (6,0) Inv
[clickIDY_compareCart_labelName_13(p);clickIDY_compareCart_labelName_13(q)] ~ [] (4,0) Inv
[clickHID_IDY_priceSlider_0_4_0_button(p);clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] ~ [] (2,0) Inv
[changeIDY_priceSlider(p);itemclickButtonBar0(q)] ~ [] (2,0) Inv
[changeIDY_priceSlider(p);clickHID_IDY_priceSlider_0_4_0_button(q)] ~ [] (7,0) Inv
[changeIDY_priceSlider(p);clickHID_IDY_priceSlider_0_4_1_button(q)] ~ [] (5,0) Inv
[clickIDY_buttonLocate(p);clickOK(q)] ~ [] (4,0) Inv
[closeIDY_addressState(p);clickIDY_buttonLocate(q)] ~ [] (2,0) Inv
[changeIDY_addressState(p);closeIDY_addressState(q)] ~ [] (3,0) Inv
[openIDY_addressState(p);closeIDY_addressState(q)] ~ [] (2,0) Inv
[openIDY_addressState(p);changeIDY_addressState(q)] ~ [] (3,0) Inv
[clickHID_IDY_addressState_1_button(p);openIDY_addressState(q)] ~ [] (7,0) Inv
[clickIDY_textFeature_11(p);clickIDY_cancas_11(q)] ~ [] (2,0) Inv
[clickHID_IDY_priceSlider_0_4_1_button(p);changeIDY_priceSlider(q)] ~ [] (2,0) Inv
[typeIDY_addressStreet(p);typeIDY_addressStreet(q)] ~ [] (2,0) Inv
[clickIDY_addressStreet(p);clickIDY_addresscity(q)] ~ [] (2,0) Inv
[clickIDY_checkout_phonenr(p);clickIDY_checkout_phonenr(q)] ~ [] (4,0) Inv
[clickIDY_checkout_phonenr(p);clickIDY_checkout_zipcode(q)] ~ [] (2,0) Inv
[clickIDY_myphonenr1(p);clickIDY_myphonenr2(q)] ~ [] (2,0) Inv
[clickIDY_checkbox_remember(p);clickIDY_buttonLogin(q)] ~ [] (2,0) Inv
[clickImage6(p);clickImage7(q)] ~ [] (2,0) Inv
[clickImage6(p);clickImage6(q)] ~ [] (2,0) Inv
[clickIDY_checkout_zipcode(p);typeIDY_checkout_zipcode(q)] ~ [] (2,0) Inv
[clickIDY_checkout_zipcode(p);clickIDY_checkout_zipcode(q)] ~ [] (6,0) Inv
[clickIDY_addressZip(p);clickIDY_buttonLocate(q)] ~ [] (2,0) Inv
