[closeIDY_filterPanel_comboboxSeries(p)] ~ [] (9,0) Skip
[openIDY_filterPanel_comboboxSeries(p)] ~ [] (9,0) Skip
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p)] ~ [] (12,0) Skip
[clickOK(p)] ~ [] (13,0) Skip
[clickIDY_textFeature_17(p)] ~ [] (7,0) Skip
[clickdescriptionText(p)] ~ [] (12,0) Skip
[typeIDY_myphonenr1(p)] ~ [] (9,0) Skip
[clickIDY_myphonenr1(p)] ~ [] (8,0) Skip
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p);openIDY_filterPanel_comboboxSeries(q)] ~ [openIDY_filterPanel_comboboxSeries(q)] (9,0) Zero
[clickIDY_submit_order(p);clickOK(q)] ~ [clickOK(q)] (11,0) Zero
[clickIDY_myphonenr2(p);typeIDY_myphonenr1(q)] ~ [typeIDY_myphonenr1(q)] (9,0) Zero
[clickIDY_myphonenr1(p);typeIDY_myphonenr1(q)] ~ [typeIDY_myphonenr1(q)] (45,0) Zero
[clickOK(p);clickIDY_myphonenr1(q)] ~ [clickIDY_myphonenr1(q)] (8,0) Zero
[typeIDY_myphonenr2(p);clickIDY_myphonenr1(q)] ~ [clickIDY_myphonenr1(q)] (8,0) Zero
[clickIDY_pwd(p);clickIDY_myphonenr1(q)] ~ [clickIDY_myphonenr1(q)] (8,0) Zero
[clickIDY_myphonenr2(p);clickIDY_myphonenr1(q)] ~ [clickIDY_myphonenr1(q)] (8,0) Zero
[typeIDY_myphonenr1(p);clickIDY_myphonenr1(q)] ~ [clickIDY_myphonenr1(q)] (8,0) Zero
[itemclickButtonBar0(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (34,0) Idemp
[clickdescriptionText(p);clickdescriptionText(q)] ~ [clickdescriptionText(q)] (8,0) Idemp
[typeIDY_myphonenr1(p);typeIDY_myphonenr1(q)] ~ [typeIDY_myphonenr1(q)] (27,0) Idemp
[clickIDY_myphonenr1(p);clickIDY_myphonenr1(q)] ~ [clickIDY_myphonenr1(q)] (16,0) Idemp
[clickIDY_textFeature_17(p);clickIDY_cancas_17(q)] ~ [clickIDY_cancas_17(q);clickIDY_textFeature_17(p)] (7,0) Com
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p);openIDY_filterPanel_comboboxSeries(q)] ~ [] (9,0) Inv
