[clickImage7(p)] ~ [] (38,0) Skip
[clickHID_IDY_addressState_1_button(p)] ~ [] (7,0) Skip
[clickIDY_filterPanel_buttonGo(p)] ~ [] (8,0) Skip
[closeIDY_filterPanel_comboboxSeries(p)] ~ [] (10,0) Skip
[openIDY_filterPanel_comboboxSeries(p)] ~ [] (10,0) Skip
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p)] ~ [] (12,0) Skip
[clickIDY_img_lang_French(p)] ~ [] (7,0) Skip
[clickOK(p)] ~ [] (15,0) Skip
[clickAceptar(p)] ~ [] (8,0) Skip
[clickIDY_addressStreet(p);clickImage7(q)] ~ [clickImage7(q)] (12,0) Zero
[clickOK(p);clickImage7(q)] ~ [clickImage7(q)] (12,0) Zero
[clickImage6(p);clickImage7(q)] ~ [clickImage7(q)] (11,0) Zero
[clickHID_IDY_addressState_1_button(p);openIDY_addressState(q)] ~ [openIDY_addressState(q)] (7,0) Zero
[typeIDY_addressZip(p);clickHID_IDY_addressState_1_button(q)] ~ [clickHID_IDY_addressState_1_button(q)] (8,0) Zero
[openIDY_addressState(p);clickHID_IDY_addressState_1_button(q)] ~ [clickHID_IDY_addressState_1_button(q)] (8,0) Zero
[typeIDY_filterPanel_txtInputFind(p);clickIDY_filterPanel_buttonGo(q)] ~ [clickIDY_filterPanel_buttonGo(q)] (8,0) Zero
[clickOK(p);clickIDY_filterPanel_buttonGo(q)] ~ [clickIDY_filterPanel_buttonGo(q)] (24,0) Zero
[clickIDY_myphonenr2(p);typeIDY_myphonenr1(q)] ~ [typeIDY_myphonenr1(q)] (7,0) Zero
[openIDY_filterPanel_comboboxSeries(p);changeIDY_filterPanel_comboboxSeries(q)] ~ [changeIDY_filterPanel_comboboxSeries(q)] (8,0) Zero
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p);openIDY_filterPanel_comboboxSeries(q)] ~ [openIDY_filterPanel_comboboxSeries(q)] (12,0) Zero
[itemclickButtonBar0(p);clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] ~ [clickHID_IDY_filterPanel_comboboxSeries_1_button(q)] (7,0) Zero
[clickIDY_filterPanel_cbTriband(p);changeIDY_priceSlider(q)] ~ [changeIDY_priceSlider(q)] (20,0) Zero
[clickIDY_img_lang_French(p);changeIDY_priceSlider(q)] ~ [changeIDY_priceSlider(q)] (20,0) Zero
[clickIDY_filterPanel_buttonGo(p);clickOK(q)] ~ [clickOK(q)] (40,0) Zero
[typeIDY_filterPanel_txtInputFind(p);clickOK(q)] ~ [clickOK(q)] (7,0) Zero
[typeIDY_myphonenr3(p);clickOK(q)] ~ [clickOK(q)] (7,0) Zero
[clickIDY_buttonLogin(p);clickOK(q)] ~ [clickOK(q)] (10,0) Zero
[closeIDY_filterPanel_comboboxSeries(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (7,0) Zero
[changeIDY_priceSlider(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (8,0) Zero
[clickOK(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (23,0) Zero
[clickIDY_img_lang_English(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (8,0) Zero
[clickImage7(p);clickImage7(q)] ~ [clickImage7(q)] (380,0) Idemp
[clickactive(p);clickactive(q)] ~ [clickactive(q)] (8,0) Idemp
[itemclickButtonBar0(p);itemclickButtonBar0(q)] ~ [itemclickButtonBar0(q)] (87,0) Idemp
[clicklearn_more(p);clicklearn_more(q)] ~ [clicklearn_more(q)] (12,0) Idemp
[clickOK(p);clickIDY_filterPanel_buttonGo(q)] ~ [clickIDY_filterPanel_buttonGo(q);clickOK(p)] (20,0) Com
[clickImage7(p);clickImage7(q)] ~ [] (34,0) Inv
[clickHID_IDY_filterPanel_comboboxSeries_1_button(p);openIDY_filterPanel_comboboxSeries(q)] ~ [] (10,0) Inv
[itemclickButtonBar0(p);itemclickButtonBar0(q)] ~ [] (17,0) Inv
